apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: greeters.hello.operator.io
spec:
  group: hello.operator.io
  names:
    kind: Greeter
    listKind: GreeterList
    plural: greeters
    singular: greeter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          size:
            description: Number of instances to deploy
            format: int32
            type: integer
          iamge:
            description: Base image to use
            type: string
          required:
          - size
          type: object
      type: object
  versions:
  - name: v1
    served: true
    storage: true
