apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hellos.hello.operator.io
spec:
  group: hello.operator.io
  names:
    kind: Hello
    listKind: HelloList
    plural: hellos
    singular: hello
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Hello is the Schema for the hello API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HelloSpec defines the desired state of Hello
          size:
            description: Number of instances to deploy
            format: int32
            type: integer
          iamge:
            description: Base image to use
            type: string
          istioSidecarInject:
            description: istio sidecar inject
            type: string
          publisherService:
            description: publisher service
            type: string
          type: object
      type: object
  versions:
  - name: v1
    served: true
    storage: true
