---
- name: Set version when not defined
  set_fact:
    version: "{{ image|regex_replace('^.*:(?P<tag>.*)$', '\\g<tag>') }}"
  when: version is not defined

#- name: Create namespace
#  k8s:
#   api_version: v1
#   kind: Namespace
#   name: "{{ meta.namespace }}"

- name: Create deployment
  k8s:
   definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"
   
- name: Create service
  k8s:
   definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"
